version: "3.8"
services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8081:8080" # Map host's 8080 to container's 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_service
      SPRING_DATASOURCE_USERNAME: modo
      SPRING_DATASOURCE_PASSWORD: radeon6214
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET: x9:ROu<tANZ,Q0k7c9Px
      jwt.expirationMs: "604800000"


    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16.0
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: modo
      POSTGRES_PASSWORD: radeon6214
      POSTGRES_DB: user_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
